### ISSUE TITLE
Unable to select previously selected options

### ISSUE THREAD

**Issue by EGeorge13** [nachocinalli/adapt-selectchoice#2]
When the question is reset after a fail attempt, if the user attempts to select an option they chose previously (correct or incorrect), they are unable to select. 
If the user selects an alternative option first, they can then select the original. 

No errors appear. 
Currently set to -1 attempts, but had same effect on 2 and 3 attempts.

![Before Reset](https://github.com/user-attachments/assets/05714bf0-d217-41b2-a054-ea29b8a662f5)
![After Reset](https://github.com/user-attachments/assets/04341319-7834-4556-a109-4af8e522027e)

**Comment by nachocinalli** [comment]
Hi @EGeorge13 ,
I've made a small change. Could you please try testing it again using the latest version (5.3.0)?
Thanks!

**Comment by EGeorge13** [comment]
Just tested latest version @nachocinalli, works like a charm!
Thank you so much for fixing so quickly!
